services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wallet
      MYSQL_USER: wallet_user
      MYSQL_PASSWORD: wallet_pass
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: wallet_user
      PMA_PASSWORD: wallet_pass
    ports:
      - "8081:80"
    depends_on:
      - db

  backend:
    build: ./backend
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: wallet
      DB_USER: wallet_user
      DB_PASS: wallet_pass
      DEFAULT_DISPLAY_CURRENCY: USD
      FRONTEND_URL: http://localhost:3000
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
      - mailpit
    ports:
      - "8000:80"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./mailpit-data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db_data: 